const methods = {
    GET_PLACEMARKS_DATA: 'GET_PLACEMARKS_DATA',
    GET_PLACEMARK_DATA: 'GET_PLACEMARK_DATA',
    SAVE_PLACEMARK: 'SAVE_PLACEMARK',
    AUTH: 'AUTH',
    IS_AUTHORIZED: 'IS_AUTHORIZED'
};

exports.methods = methods;