const methods = {
    GET_PLACEMARKS_DATA: 'GET_PLACEMARKS_DATA',
    GET_PLACEMARK_DATA: 'GET_PLACEMARK_DATA',
    SAVE_PLACEMARK: 'SAVE_PLACEMARK',
    UPDATE_PLACEMARK: 'UPDATE_PLACEMARK',
    DELETE_PLACEMARK: 'DELETE_PLACEMARK',
    AUTH: 'AUTH',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    IS_AUTHORIZED: 'IS_AUTHORIZED'
};

exports.methods = methods;