const initialState = {
    placemarks: [
        {
            id: 1,
            address: "с.Красное",
            coordinates: [57.5928, 40.3597],
            violationType: "",
            picture: ['1.png'],
            plastic: 0,
            metal: 0,
            glass: 0,
            paper: 0,
            household: 0,
            construction: 0,
            other: 0,
            created: "2019-07-06 21:01:40",
            renew: "2019-07-07 09:36:51",
            reporter: 0,
            comment: "полигон",
            state: "В Архиве",
            level: 5,
            price: 0,
            volume: 0
        },
        {
            id: 2,
            address: "с.Туношна ул.Набережная",
            coordinates: [57.5451, 40.116],
            violationType: "Стихийная свалка",
            picture: ['2.png'],
            plastic: 0,
            metal: 0,
            glass: 0,
            paper: 0,
            household: 0,
            construction: 0,
            other: 0,
            created: "2019-07-06 21:02:40",
            renew: "2019-07-07 00:32:44",
            reporter: 0,
            comment: "полигон",
            state: "Выполнена",
            level: 0,
            price: 0,
            volume: 0,
        },
        {
            id: 3,
            address: "п.Дорожный",
            coordinates: [57.5536, 40.1951],
            violationType: "Стихийная свалка",
            picture: ['3.png'],
            plastic: 0,
            metal: 0,
            glass: 0,
            paper: 0,
            household: 0,
            construction: 0,
            other: 0,
            created: "2019-07-06 21:04:23",
            renew: "2019-07-06 21:04:23",
            reporter: 0,
            comment: "Полигон",
            state: "Новая",
            level: 0,
            price: 0,
            volume: 0
        },
        {
            id: 4,
            address: "д.Мокеевское",
            coordinates: [57.4884, 40.1014],
            violationType: "Стихийная свалка",
            picture: ['4.png'],
            plastic: 0,
            metal: 0,
            glass: 0,
            paper: 0,
            household: 0,
            construction: 0,
            other: 0,
            created: "2019-07-06 21:05:50",
            renew: "2019-07-06 21:05:50",
            reporter: 0,
            comment: "полигон",
            state: "Новая",
            level: 0,
            price: 0,
            volume: 0
        },
        {
            id: 5,
            address: "д.Мокеевское",
            coordinates: [57.4866, 40.1028],
            violationType: "Стихийная свалка",
            picture: ['5.png'],
            plastic: 0,
            metal: 0,
            glass: 0,
            paper: 0,
            household: 0,
            construction: 0,
            other: 0,
            created: "2019-07-06 21:06:55",
            renew: "2019-07-07 00:32:25",
            reporter: 0,
            comment: "",
            state: "В работе",
            level: 0,
            price: 0,
            volume: 0
        }
    ]
};

export default initialState;